name: find_me
description: "Can you find me?"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.0
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.1.3
  riverpod_annotation: ^2.6.1
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/jpegs/

flutter_intl:
  enabled: true
  main_locale: en
  class_name: L10n
  arb_dir: lib/presentation/l10n/l10n
  output_dir: lib/presentation/l10n/generated
